name: test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: ${{ !contains(github.event.head_commit.message, 'Skip Action')}}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential flex bison libgmp-dev

    - name: Download and install PBC library
      run: |
        git clone https://github.com/WCjrCK/pbc.git
        cd pbc
        sudo ./setup
        sudo ./configure
        sudo make -j8
        sudo make install

    - name: Install gtest
      run: |
        cd /tmp
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake .
        make
        sudo make install
        sudo ldconfig

    - name: build(default BUILD_TESTS ON)
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: test
      run: |
        cd build
        ctest --output-on-failure
